# Tafsir corpus configuration - Quranic commentaries

tools:
  # Tafsir corpus - Quranic commentaries (temporarily disabled until Vectara key is available)
  vectara:
    api_key_env: VECTARA_API_KEY
    corpus_id: ${TAFSIR_VECTARA_CORPUS_KEY}
    base_url: https://api.vectara.io
    timeout: 60
    default_top_k: 10

  # Goodmem configuration (commented out - returning 0 results, needs investigation)
  # goodmem:
  #   api_key_env: GOODMEM_API_KEY
  #   base_url: ${GOODMEM_BASE_URL}
  #   timeout: 60
  #   default_top_k: 10
  #   # Space IDs from the operational doc
  #   space_ids:
  #     - efd91f05-87cf-4c4c-a04d-0a970f8d30a7  # Ibn Katheer

  # Agentset configuration
  agentset:
    api_key_env: AGENTSET_API_TOKEN
    namespace_id_env: AGENTSET_NAMESPACE_ID
    timeout: 60
    default_top_k: 10

# LLM evaluation configuration (optional - used for quality scoring)
llm:
   model: claude-sonnet-4-5
   api_key_env: ANTHROPIC_API_KEY
   max_tokens: 16384
   temperature: 0.1
